FROM lscr.io/linuxserver/webtop:ubuntu-xfce
LABEL org.opencontainers.image.source https://github.com/yogendra/cna-tools
RUN  curl -sSL https://raw.githubusercontent.com/yogendra/dotfiles/master/scripts/jumpbox-init.sh | bash -s -- common k8s azure aws gcp

