apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  labels:
    io.kompose.service: webtop
  name: webtop
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webtop
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (HEAD)
      labels:
        io.kompose.service: webtop
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: SUBFOLDER
              value: /
            - name: TZ
              value: Asia/Singapore
          image: lscr.io/linuxserver/webtop:ubuntu-xfce
          name: webtop
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "400m"
              memory: "2024Mi"
            limits:
              cpu: "800m"
              memory: "4024Mi"
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /config
              name: webtop-claim0
            # - mountPath: /dev/shm
            #   name: dshm
      restartPolicy: Always
      volumes:
        - name: webtop-claim0
          persistentVolumeClaim:
            claimName: webtop-claim0
        # - name: dshm
        #   emptyDir:
        #     medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  labels:
    io.kompose.service: webtop
  name: webtop
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      nodePort: 32000
  selector:
    io.kompose.service: webtop
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: webtop-claim0
  name: webtop-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
