name: Jumpbox Docker Build

on: [push]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Prepare Secrets
        run: |
          echo "${{ secrets.SECRETS_SH }}" >> $GITHUB_WORKSPACE/config/secrets.sh
      - name: Login to Docker Registry
        run: |
          docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.REGISTRY_ADDRESS }}
      - name: Build Docker Image
        run: |
          make all
      - name: Test Docker Image
        run: |
          echo WIP
      - name: Push Image
        run: |
          docker push ${{secrets.REGISTRY_ADDRESS}}/${{ secrets.REGISTRY_USERNAME}}/pcf-jumpbox:latest
