name: Jumpbox Docker Build

on: [push]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    services:
      secrets:
        image: nginx
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Prepare Secrets
        run: |
          echo "${{ secrets.SECRETS_SH }}" >> $GITHUB_WORKSPACE/config/secrets.sh
          docker cp $GITHUB_WORKSPACE/config/secrets.sh secrets:/usr/share/nginx/html/secrets.sh
      - name: Test Secrets Server
        run: test $(docker run --name secrets-consumer --rm -t busybox wget -qO- http://secrets/secrets.sh | wc -l) -gt 0
      - name: Build Docker Image
        run: |
          build_secrets_location=http://secret/secrets.sh          
          docker build -t yogendra/pcf-jumpbox:latest   -f yogendra_pcf-jumpbox.Dockerfile .
      - name: Test Docker Image
        run: |
          echo WIP
      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          login-server: ${{ secrets.REGISTRY_ADDRESS }}
      - name: Push Docker Image
        run: |
          docker push yogendra/pcf-jumpbox:latest
