name: Jumpbox Docker Build

on: [push]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    services:
      secrets-server:
        image: nginx
        ports:
          - 80:80
        options: --name secrets-server --hostname secrets-server
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Prepare Secrets
        run: |
          echo "${{ secrets.SECRETS_SH }}" >> $GITHUB_WORKSPACE/config/secrets.sh
          docker cp $GITHUB_WORKSPACE/config/secrets.sh secrets-server:/usr/share/nginx/html/secrets.sh
      - name: Build Docker Image
        run: |
          DOCKER_BUILD_NETWORK=$(docker network ls -f label=e87b52 --format "{{.Name}}" | head -1)            
          docker build --network $DOCKER_BUILD_NETWORK -t yogendra/pcf-jumpbox:latest -f yogendra_pcf-jumpbox.Dockerfile .
      - name: Test Docker Image
        run: |
          echo WIP
      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          login-server: docker.io
      - name: Push Docker Image
        run: |
          docker push yogendra/pcf-jumpbox:latest
