name: Jumpbox Docker Build

on: [push]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    services:
      secrets:
        image: nginx
        ports:
          - 80:80
        volumes:
          - ${{ github.workspace }}:/usr/share/nginx/html
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Prepare Secrets
        run: |
          echo "${{ secrets.SECRETS_SH }}" >> ${GITHUB_WORKSPACE}/secrets.sh
          ls -l
      - name: Test Secrets Server
        run: |
          secrets="$(docker run --rm -t busybox wget -O- http://localhost/secrets.sh)"
          echo $secrets | wc -l
          [[ -z $secrets ]] && exit 1
      - name: Build Docker Image
        run: |
          build_secrets_location=http://localhost/secrets.sh
          docker build -t yogendra/pcf-jumpbox:latest   -f yogendra_pcf-jumpbox.Dockerfile .
      - name: Test Docker Image
        run: |
          echo WIP
      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          login-server: ${{ secrets.REGISTRY_ADDRESS }}
      - name: Push Docker Image
        run: |
          docker push yogendra/pcf-jumpbox:latest
