name: Jumpbox Docker Build

on: [push]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    services:
      secrets-server:
        image: nginx
        ports:
          - 80/tcp
#         options: --name secrets-server --hostname secrets-server
        volumes:
          - ${{ github.workspace }}:/usr/share/nginx/html:ro
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Prepare Secrets
        run: |
          echo "${{ secrets.SECRETS_SH }}" >> $GITHUB_WORKSPACE/config/secrets.sh
#       - name: Build Docker Image
#         run: |
#           DOCKER_BUILD_NETWORK=$(docker network ls -f label=d00b33 --format "{{.Name}}" | head -1)
#           echo DOCKER_BUILD_NETWORK=$DOCKER_BUILD_NETWORK
#           docker build --network $DOCKER_BUILD_NETWORK -t ${{secrets.REGISTRY_ADDRESS}}/${{ secrets.REGISTRY_USERNAME}}/pcf-jumpbox:latest -f yogendra_pcf-jumpbox.Dockerfile .
#       - name: Test Docker Image
#         run: |
#           echo WIP
#       - name: Login to Docker Registry
#         run: |
#           docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.REGISTRY_ADDRESS }}
#       - name: Push Image
#         run: |
#           docker push ${{secrets.REGISTRY_ADDRESS}}/${{ secrets.REGISTRY_USERNAME}}/pcf-jumpbox:latest
      - name: testService
#         uses: docker://alpine:3.8
        run: |
          docker build -f test-build.Dockerfile --build-arg url=http://localhost:${{ job.services.secrets-server.ports['80'] }}/README.md -t test-build .
