name: Tanzu Jumpbox

on: 
  push:
    paths:
    - 'yogendra/tanzu-jumpbox/**'
    - 'Makefile'
    - '.github/workflows/tanzu-jumpbox.yml'
  workflow_run:
    workflows: 
    - Ubuntu
    types: 
    - completed
  workflow_dispatch:

env:
  docker_image_name: tanzu-jumpbox
  docker_context: ${{github.workspace}}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the GHCR Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to the Dockerhub Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_ADDRESS }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{env.docker_context}}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.REGISTRY_USERNAME }}/${{env.docker_image_name}}:latest
            ${{ secrets.REGISTRY_USERNAME }}/${{env.docker_image_name}}:${{github.sha}}
            ghcr.io/${{ github.actor }}/${{env.docker_image_name}}:latest
            ghcr.io/${{ github.actor }}/${{env.docker_image_name}}:${{github.sha}}
