name: YB GUI Jumpbox

on: 
  push:
    paths:
    - 'yogendra/yb-gui-jumpbox/**'
    - 'Makefile'
    - '.github/workflows/yb-gui-jumpbox.yml'
  workflow_dispatch:
  

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the GHCR Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to the Dockerhub Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ secrets.REGISTRY_ADDRESS }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      # - name: Build Docker Image
      #   run: |
      #     make yb_gui_jumpbox
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: yogendra/yb_gui_jumpbox
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.REGISTRY_USERNAME }}/yb-gui-jumpbox:latest
            ${{ secrets.REGISTRY_USERNAME }}/yb-gui-jumpbox:${{github.sha}}
            ghcr.io/${{ github.actor }}/yb-gui-jumpbox:latest
            ghcr.io/${{ github.actor }}/yb-gui-jumpbox:${{github.sha}}
